language: ruby
rvm:
- 2.1

# install jekyll from gemfile
install: true

# build site
scripts: 
	- chmod +x ./scripts/build.sh

# deploy to netlify
after_success:
	- chmod +x ./scripts/deploy.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master